---
- hosts: localhost
  connection: local
  tasks:
  - name: ensure sudo not asking for password
    copy:
      content: '%wheel  ALL=(ALL)	NOPASSWD: ALL'
      dest: /etc/sudoers.d/nopasswd
  - name: add missing resolution
    copy:
      content: |
        Section "Monitor"
          Identifier "eDP-1"
          Modeline "1920x1080_60.00" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -HSync +Vsync
        EndSection
      dest: /etc/X11/xorg.conf.d/10-monitor.conf
