---
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution }}
    - group_by: key={{ ansible_architecture }}

- hosts: Fedora
  roles:
    - fedora-quirks

- hosts: all
  roles:
    - common
    - virtualbox
    - develop

