---
- hosts: localhost
  connection: local
  tasks:
  - name: ensure sudo not asking for password
    copy:
      content: '%sudo  ALL=(ALL)	NOPASSWD: ALL'
      dest: /etc/sudoers.d/nopasswd
  - name: install zsh
    package: name=zsh state=present
  - name: install emacs
    package: name=emacs state=present
  - name: install git
    package: name=git state=present
  - name: install stow
    package: name=stow state=present
