- name: add insync repo key
  apt_key:
    id: ACCAF35C
    keyserver: keyserver.ubuntu.com
    state: present

- name: add insync repo
  apt_repository:
    filename: insync
    repo: "deb http://apt.insync.io/ubuntu {{ ansible_distribution_release }} non-free contrib"
    state: present

- name: add chrome repo key
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: add chrome repo
  apt_repository:
    filename: google-chrome
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
