- include: "add-repo-{{ ansible_distribution }}.yml"
- include: insync.yml
- include: dropbox.yml

- include: audio.yml
  when: ansible_distribution == 'Ubuntu'

- name: install desktop packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - hplip-gui
  - pipewire
  - google-chrome-stable
