- name: Install development tools
  dnf:
    name: '@development'
    state: present

- name: install libraries
  package:
    name: "{{ item }}" 
    state: present
  with_items:
    - openssl-devel
    - readline-devel
    - zlib-devel
    - bzip2-devel
    - sqlite-devel
    - libcurl-devel
    - libffi-devel
    - python3-devel
    - xz-devel
    - findutils
