- name: add docker apt key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable"
    state: present  

- name: add vscode apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add vscode repository
  apt_repository:
    filename: vscode
    repo: "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main"
    state: present