- name: install libraries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libreadline-dev
    - libzip-dev
    - libbz2-dev
    - libsqlite3-dev
    - libcurl4-openssl-dev
    - libsecret-1-dev
    - libffi-dev
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - liblzma-dev
