- name: install git
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - git-lfs

- name: install libsecret credential helper
  shell:
    cmd: make
    creates: /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
    chdir: /usr/share/doc/git/contrib/credential/libsecret
