# - include: "add-repo-{{ ansible_distribution }}.yml"
# - include: docker.yml

- include: "add-lib-{{ ansible_distribution }}.yml"
- include: docker.yml
- include: git.yml

- name: install vscode
  package:
    name: code
    state: present

