- include: "add-repo-{{ ansible_distribution }}.yml"
- include: docker.yml
- include: stack.yml

- name: install {{ item }}
  package: name={{ item }} state=present
  with_items:
    - git
    - "{{ jre8_package }}"
    - "{{ jdk8_package }}"
    # develop libs
    - openssl-devel
    - readline-devel
    - zlib-devel
