- include: "add-repo-{{ ansible_distribution }}.yml"
- include: docker.yml
- include: stack.yml

- name: install {{ item }}
  package: name={{ item }} state=present
  with_items:
    - git
    # develop libs
    - openssl-devel
    - readline-devel
    - zlib-devel
    - bzip2-devel
    - sqlite-devel

- name: install terraform
  unarchive:
    dest: /usr/local/bin
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_{{ ansible_system | lower }}_{{ platform_arch }}.zip
    remote_src: yes
    keep_newer: yes
    mode: 0755
