- name: install packages
  package: name={{ item }} state=present
  with_items:
    - zsh
    - emacs
    - stow
    - fasd
    - hplip-gui
    - icedtea-web

- include: "{{ ansible_distribution }}/packages.yml"
