- name: install zsh
  package: name=zsh state=present
- name: install emacs
  package: name=emacs state=present
- name: install git
  package: name=git state=present
- name: install stow
  package: name=stow state=present
