- name: install packages
  package: name={{ item }} state=present
  with_items:
    - zsh
    - emacs
    - git
    - stow
    - fasd
    - hplip-gui
    - playonlinux

- include: "{{ ansible_distribution }}/packages.yml"
