- name: add {{ admin_group }} group to cups admin
  replace:
    dest: /etc/cups/cups-files.conf
    regexp: ^SystemGroup(.*?)(\s+{{ admin_group }})?$
    replace: SystemGroup\1 {{ admin_group }}
  notify:
    - restart cups
