- name: add wheel group to cups admin
  replace:
    dest: /etc/cups/cups-files.conf
    regexp: ^SystemGroup(.*?)(\s+wheel)?$
    replace: SystemGroup\1 {{ admin_group }}
  notify:
    - restart cups
