- name: add rpmfusion gpg keys
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
- name: add rpmfusion nonfree gpg keys
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
- name: add rpmfusion repos
  dnf:
    name: https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ansible_distribution_version}}.noarch.rpm
    state: present
  with_items:
  - free
  - nonfree

- name: enable snap store
  package:
    name: snapd
    state: present

- name: enable snap classic mode
  file:
    path: /snap
    src: /var/lib/snapd/snap
    state: link

- name: install ansible dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python-dnf
