- name: add rpmfusion repos
  dnf:
    name: https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ansible_distribution_version}}.noarch.rpm
    state: present
  with_items:
    - free
    - nonfree

- name: install ansible dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dnf
